/* Kundali input, geocoding, calculation orchestration, and result rendering. */
const kundaliState = {name:'',gender:'',dob:'',dobAd:'',dobBsYear:'',dobBsMonth:'',dobBsDay:'',tob:'',pob:'',country:'',language:'en',location:null,timezone:'',submitted:false,chart:null,error:''};
function kundaliEsc(value){return String(value==null?'':value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function kundaliFormatDegree(value){const degrees=((Number(value)%360)+360)%360;const within=degrees-Math.floor(degrees/30)*30;return `${Math.floor(within)}°${String(Math.floor((within%1)*60)).padStart(2,'0')}'`;}
const kundaliBsMonthsEn=['Baisakh','Jestha','Asar','Shrawan','Bhadra','Aswin','Kartik','Mangsir','Poush','Magh','Falgun','Chaitra'];
const kundaliBsMonthsNe=['बैशाख','जेठ','असार','श्रावण','भाद्र','आश्विन','कार्तिक','मंसिर','पौष','माघ','फाल्गुण','चैत्र'];
function kundaliDateConstructor(){return typeof NepaliDate==='function'?NepaliDate:(NepaliDate&&NepaliDate.default);}
function kundaliBsToAd(y,m,d){try{const C=kundaliDateConstructor();if(!C)return null;const nd=new C(parseInt(y,10),parseInt(m,10)-1,parseInt(d,10));const js=nd.toJsDate();if(!js||isNaN(js.getTime()))return null;return `${js.getFullYear()}-${String(js.getMonth()+1).padStart(2,'0')}-${String(js.getDate()).padStart(2,'0')}`;}catch(e){return null;}}
function kundaliAdToBs(adStr){try{const C=kundaliDateConstructor();if(!C||!adStr)return null;const p=adStr.split('-').map(Number);const nd=new C(new Date(p[0],p[1]-1,p[2]));return {year:nd.getYear(),month:nd.getMonth()+1,day:nd.getDate()};}catch(e){return null;}}
function kundaliYearOptions(sel){let s='<option value="">--</option>';for(let y=2000;y<=2090;y++){s+=`<option value="${y}" ${String(sel)===String(y)?'selected':''}>${y} वि.सं.</option>`;}return s;}
function kundaliMonthOptions(sel){const names=(typeof LANG!=='undefined'&&LANG==='ne')?kundaliBsMonthsNe:kundaliBsMonthsEn;let s='<option value="">--</option>';names.forEach((n,i)=>{const v=i+1;s+=`<option value="${v}" ${String(sel)===String(v)?'selected':''}>${n}</option>`;});return s;}
function kundaliDayOptions(sel){let s='<option value="">--</option>';for(let d=1;d<=32;d++){s+=`<option value="${d}" ${String(sel)===String(d)?'selected':''}>${d}</option>`;}return s;}
function setKundaliBs(part,value){
  if(part==='year')kundaliState.dobBsYear=value;
  if(part==='month')kundaliState.dobBsMonth=value;
  if(part==='day')kundaliState.dobBsDay=value;
  if(kundaliState.dobBsYear&&kundaliState.dobBsMonth&&kundaliState.dobBsDay){const ad=kundaliBsToAd(kundaliState.dobBsYear,kundaliState.dobBsMonth,kundaliState.dobBsDay);if(ad){kundaliState.dob=ad;kundaliState.dobAd=ad;}else{kundaliState.dob='';}}
  renderKundali();
}
function setKundaliAd(value){
  kundaliState.dob=value;kundaliState.dobAd=value;
  if(value){const bs=kundaliAdToBs(value);if(bs){kundaliState.dobBsYear=bs.year;kundaliState.dobBsMonth=bs.month;kundaliState.dobBsDay=bs.day;}}
  renderKundali();
}
function kundaliLocationLabel(location){return location?`${location.name}, ${location.country}`:'Search for a birthplace';}
async function resolveKundaliTimezone(latitude,longitude){
  const sources=[`https://timeapi.io/api/timezone/coordinate?latitude=${latitude}&longitude=${longitude}`,`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en`];
  for(let i=0;i<sources.length;i++){
    try{const response=await fetch(sources[i]);if(!response.ok)continue;const data=await response.json();const zone=(data&&(data.timeZone||data.timezone||data.timezoneName))||'';if(zone)return zone;}catch(error){}
  }
  return '';
}
async function resolveTypedKundaliLocation(){
  const placeInput=document.getElementById('kPob'), countryInput=document.getElementById('kCountry');
  if(!placeInput||!placeInput.value.trim()) return false;
  const query=`${placeInput.value.trim()}${countryInput&&countryInput.value.trim()?`, ${countryInput.value.trim()}`:''}`;
  try{
    let place,address;const response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=1&q=${encodeURIComponent(query)}`,{headers:{Accept:'application/json'}});
    if(response.ok){const places=await response.json();place=places[0];address=place&&place.address||{};}else if(response.status===429||response.status>=500){const fallback=await fetch(`https://photon.komoot.io/api/?limit=1&q=${encodeURIComponent(query)}`);if(fallback.ok){const result=(await fallback.json()).features?.[0];if(result){const properties=result.properties||{};place={lat:result.geometry.coordinates[1],lon:result.geometry.coordinates[0],display_name:result.properties?.name?`${result.properties.name}, ${result.properties.country||''}`:query};address={city:properties.city||properties.town||properties.village||properties.locality,name:properties.name,country:properties.country,countrycode:properties.countrycode};}}}
    if(!place)throw new Error((typeof LANG!=='undefined'&&LANG==='ne')?'जन्मस्थान भेटिएन।':'Birthplace could not be found.');
    kundaliState.location={name:address.city||address.town||address.village||address.locality||address.name||place.name,country:address.country||countryInput.value.trim(),countryCode:(address.country_code||address.countrycode||'').toUpperCase(),latitude:Number(place.lat),longitude:Number(place.lon),displayName:place.display_name};kundaliState.pob=placeInput.value.trim();kundaliState.country=countryInput.value.trim()||kundaliState.location.country;
    if(countryInput&&!countryInput.value.trim()) countryInput.value=kundaliState.location.country;
    kundaliState.timezone=await resolveKundaliTimezone(kundaliState.location.latitude,kundaliState.location.longitude);if(!kundaliState.timezone)throw new Error('Timezone could not be resolved');
    return true;
  }catch(error){kundaliState.location=null;kundaliState.timezone='';kundaliState.error=error.message;return false;}
}
async function searchKundaliLocations(query){
  const list=document.getElementById('kundaliLocationResults'); if(!list||query.trim().length<3){if(list)list.innerHTML='';return;}
  list.innerHTML='<div class="location-loading">Searching locations...</div>';
  try{const response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=6&q=${encodeURIComponent(query)}`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Location search failed');const places=await response.json();window._kundaliPlaces=places;list.innerHTML=places.length?places.map((place,index)=>`<button type="button" class="location-result" onclick="selectKundaliLocation(${index})"><strong>${kundaliEsc(place.display_name.split(',').slice(0,2).join(', '))}</strong><span>${kundaliEsc(place.display_name)}</span></button>`).join(''):'<div class="location-loading">No matching locations found.</div>';}catch(error){list.innerHTML=`<div class="location-loading">${kundaliEsc(error.message)}. Check your connection.</div>`;}
}
async function selectKundaliLocation(index){
  const place=(window._kundaliPlaces||[])[index];if(!place)return;const address=place.address||{};
  kundaliState.location={name:address.city||address.town||address.village||address.municipality||place.name,country:address.country||'',countryCode:(address.country_code||'').toUpperCase(),latitude:Number(place.lat),longitude:Number(place.lon),displayName:place.display_name};kundaliState.pob=kundaliState.location.name;kundaliState.country=kundaliState.location.country;
  document.getElementById('kPob').value=kundaliLocationLabel(kundaliState.location);document.getElementById('kCountry').value=kundaliState.country;document.getElementById('kundaliLocationResults').innerHTML=`<div class="location-selected">Selected: ${kundaliEsc(place.display_name)}</div>`;
  try{kundaliState.timezone=await resolveKundaliTimezone(kundaliState.location.latitude,kundaliState.location.longitude);document.getElementById('kundaliTimezoneHint').textContent=kundaliState.timezone?((typeof LANG!=='undefined'&&LANG==='ne')?`ऐतिहासिक समयक्षेत्र: ${kundaliState.timezone}`:`Historical timezone: ${kundaliState.timezone}`):((typeof LANG!=='undefined'&&LANG==='ne')?'समयक्षेत्र पत्ता लागेन':'Timezone could not be resolved');}catch(error){kundaliState.timezone='';document.getElementById('kundaliTimezoneHint').textContent=(typeof LANG!=='undefined'&&LANG==='ne')?'समयक्षेत्र जाँच उपलब्ध छैन; प्रमाणित नभएसम्म कुण्डली निर्माण बन्द छ।':'Timezone lookup unavailable; generation is disabled until it can be verified.';}
}
function renderKundali(){
  const panel=document.getElementById('kundaliPanel');if(!panel)return;const resultPanel=document.getElementById('kundaliChartPanel');if(resultPanel&&kundaliState.submitted&&kundaliState.chart){renderKundaliResult();return;}
  const nepali=typeof LANG!=='undefined'&&LANG==='ne';
  const labels=nepali?{eyebrow:'वैदिक जन्म कुण्डली',title:'स्वचालित कुण्डली निर्माण',intro:'जन्मस्थान र देश आफैं टाइप गर्नुहोस्। स्थान, ऐतिहासिक समयक्षेत्र, UTC रूपान्तरण र लाहिरी साइडेरियल गणना सुरक्षित गरिन्छ।',name:'पूरा नाम *',gender:'लिङ्ग',prefer:'भन्न नचाहने',female:'महिला',male:'पुरुष',other:'अन्य',dob:'जन्म मिति *',dobAd:'जन्म मिति (English / AD) *',dobBs:'जन्म मिति (नेपाली / BS)',tob:'ठ्याक्कै स्थानीय जन्म समय *',place:'जन्मस्थान *',placeHint:'शहर, गाउँ वा नगरपालिका',country:'देश *',current:'हालको स्थान',optional:'वैकल्पिक',language:'मनपर्ने भाषा',choose:'जन्मस्थान र देश टाइप गर्नुहोस्; गणनाअघि स्थान स्वतः जाँच हुनेछ।',disclaimer:'खगोलीय मानहरू निश्चित ephemeris इन्जिनबाट गणना हुन्छन्। स्थान, समयक्षेत्र वा ephemeris प्रमाणित नभए अनुमानित कुण्डली देखाइँदैन।',submit:'पूर्ण कुण्डली निर्माण गर्नुहोस्'}:{eyebrow:'Vedic birth chart',title:'Automated Kundali Nirmad',intro:'Type the birthplace and country yourself. Coordinates, historical timezone, UTC conversion, and Lahiri sidereal calculations are stored with the result.',name:'Full name *',gender:'Gender',prefer:'Prefer not to say',female:'Female',male:'Male',other:'Other',dob:'Date of birth *',dobAd:'Date of birth (English / AD) *',dobBs:'Date of birth (Nepali / BS)',tob:'Exact local birth time *',place:'Birthplace *',placeHint:'Type city, town, or village',country:'Country *',current:'Current location',optional:'Optional',language:'Preferred language',choose:'Type the birthplace and country; the location will be verified before calculation.',disclaimer:'Astronomical values come from the configured ephemeris engine. The system will not show an estimated chart when location, timezone, or ephemeris data cannot be verified.',submit:'Generate complete Kundali'};
  const selectedLanguage=nepali?'ne':(kundaliState.language||'en');
  const timezoneHint=kundaliState.timezone?(nepali?`ऐतिहासिक समयक्षेत्र: ${kundaliState.timezone}`:`Historical timezone: ${kundaliState.timezone}`):labels.choose;
  const placeHint=nepali?'शहर, गाउँ वा नगरपालिका टाइप गर्नुहोस्':'Type city, town, or village';
  panel.innerHTML=`<div class="kundali-form-header"><span class="eyebrow">${labels.eyebrow}</span><h2>${labels.title}</h2><p>${labels.intro}</p></div><div class="form-grid cols-2"><div class="field"><label for="kName">${labels.name}</label><input id="kName" required value="${kundaliEsc(kundaliState.name)}" oninput="kundaliState.name=this.value"></div><div class="field"><label for="kGender">${labels.gender}</label><select id="kGender" onchange="kundaliState.gender=this.value"><option value="">${labels.prefer}</option><option>${labels.female}</option><option>${labels.male}</option><option>${labels.other}</option></select></div><div class="field"><label for="kDob">${labels.dobAd}</label><input type="date" id="kDob" required value="${kundaliState.dob}" onchange="setKundaliAd(this.value)"></div><div class="field"><label>${labels.dobBs}</label><div style="display:flex;gap:6px;"><select onchange="setKundaliBs('year',this.value)">${kundaliYearOptions(kundaliState.dobBsYear)}</select><select onchange="setKundaliBs('month',this.value)">${kundaliMonthOptions(kundaliState.dobBsMonth)}</select><select onchange="setKundaliBs('day',this.value)">${kundaliDayOptions(kundaliState.dobBsDay)}</select></div><small>${nepali?'मिति एउटा मात्र भर्नुहोस्; अर्को स्वतः रूपान्तरण हुन्छ।':'Fill either date; the other auto-converts.'}</small></div><div class="field"><label for="kTob">${labels.tob}</label><input type="time" id="kTob" required value="${kundaliState.tob}" onchange="kundaliState.tob=this.value"></div><div class="field location-field"><label for="kPob">${labels.place}</label><input id="kPob" type="text" autocomplete="off" placeholder="${placeHint}" value="${kundaliEsc(kundaliState.pob)}" oninput="kundaliState.pob=this.value;kundaliState.location=null;kundaliState.timezone='';searchKundaliLocations(this.value)"><div class="location-results" id="kundaliLocationResults"></div><small id="kundaliTimezoneHint"></small></div><div class="field"><label for="kCountry">${labels.country}</label><input id="kCountry" type="text" autocomplete="off" value="${kundaliEsc(kundaliState.country)}" oninput="kundaliState.country=this.value;kundaliState.location=null;kundaliState.timezone=''"></div><div class="field"><label for="kCurrentLocation">${labels.current}</label><input id="kCurrentLocation" placeholder="${labels.optional}"></div><div class="field"><label for="kLanguage">${labels.language}</label><select id="kLanguage" onchange="kundaliState.language=this.value;renderKundali()"><option value="en" ${selectedLanguage==='en'?'selected':''}>English</option><option value="ne" ${selectedLanguage==='ne'?'selected':''}>नेपाली</option></select></div></div><div class="disclaimer-box">${labels.disclaimer}</div><button class="btn btn-gold btn-block" style="margin-top:18px" onclick="submitKundali()">${labels.submit}</button>`;
}
async function submitKundali(){
  const errorHint=document.getElementById('kundaliTimezoneHint');const nepali=typeof LANG!=='undefined'&&LANG==='ne';kundaliState.name=document.getElementById('kName').value.trim();const adInput=document.getElementById('kDob').value;kundaliState.dob=(adInput||kundaliState.dobAd||'');kundaliState.tob=document.getElementById('kTob').value;const place=document.getElementById('kPob').value.trim();const country=document.getElementById('kCountry').value.trim();
    if(!kundaliState.name){if(errorHint)errorHint.textContent=nepali?'पूरा नाम लेख्नुहोस्।':'Please enter your full name.';showToast('Please enter your full name.');return;}if(!kundaliState.dob){if(errorHint)errorHint.textContent=nepali?'जन्म मिति लेख्नुहोस्।':'Please enter your date of birth.';showToast('Please enter your date of birth.');return;}if(!kundaliState.tob){if(errorHint)errorHint.textContent=nepali?'ठ्याक्कै जन्म समय लेख्नुहोस्।':'Please enter your exact birth time.';showToast('Please enter your exact birth time.');return;}if(!place){if(errorHint)errorHint.textContent=nepali?'जन्मस्थान लेख्नुहोस्।':'Please type your birthplace.';showToast('Please type your birthplace.');return;}if(!country){if(errorHint)errorHint.textContent=nepali?'देश लेख्नुहोस्।':'Please type your country.';showToast('Please type your country.');return;}
  if(errorHint)errorHint.textContent=nepali?'कुण्डली गणना सुरु हुँदैछ...':'Kundali calculation started...';if(!kundaliState.location)await resolveTypedKundaliLocation();if(!kundaliState.location){if(errorHint)errorHint.textContent=kundaliState.error||'Birthplace verification failed.';showToast('Birthplace verification failed.');return;}if(!kundaliState.timezone){if(errorHint)errorHint.textContent='Timezone verification failed.';showToast('The timezone for this birthplace could not be verified.');return;}
  const button=document.querySelector('#kundaliPanel button.btn-gold');if(button){button.disabled=true;button.textContent=nepali?'गणना हुँदैछ...':'Calculating...';}try{kundaliState.chart=await window.KUNDALI_ENGINE.calculate({name:kundaliState.name,date:kundaliState.dob,time:kundaliState.tob,location:kundaliState.location,timezone:kundaliState.timezone,ayanamsha:'lahiri'});kundaliState.submitted=true;await persistKundali();renderKundali();}catch(error){if(button){button.disabled=false;button.textContent=nepali?'पूर्ण कुण्डली निर्माण गर्नुहोस्':'Generate complete Kundali';}if(errorHint)errorHint.textContent=error.message;showToast(error.message);}
}
async function persistKundali(){const payload=JSON.stringify(kundaliState);const key=((SITE_CONFIG.storageKeys||{}).kundali||'kundali_')+Date.now();if(window.JYOTISH_HELPERS&&window.JYOTISH_HELPERS.safeStorageSet)await window.JYOTISH_HELPERS.safeStorageSet(key,payload);if(typeof saveAuthenticatedSubmission==='function')await saveAuthenticatedSubmission('kundali',kundaliState);}
function kundaliChartSvg(title,placements){const cells=Array.from({length:12},(_,house)=>{const items=(placements||[]).filter(p=>p.house===house+1).map(p=>p.short).join(' ');return `<div class="rashi-cell"><b>${house+1}</b><span>${items||'-'}</span></div>`;}).join('');return `<div class="chart-card"><h3>${title}</h3><div class="rashi-chart">${cells}</div></div>`;}
function renderKundaliResult(){const c=kundaliState.chart;const target=document.getElementById('kundaliChartPanel')||document.getElementById('kundaliPanel');const planetRows=c.planets.map(p=>`<tr><td>${kundaliEsc(p.name)}</td><td>${kundaliEsc(p.sign)}</td><td>${kundaliFormatDegree(p.longitude)}</td><td>${kundaliEsc(p.nakshatra)} ${p.pada}</td><td>${p.house}</td><td>${p.retrograde?'Yes':'No'}</td></tr>`).join('');target.style.display='block';target.innerHTML=`<div class="kundali-report"><div class="report-heading"><div><span class="eyebrow">Deterministic calculation report</span><h2>${kundaliEsc(c.name)}</h2><p>${c.birthDate} at ${c.birthTime} | ${kundaliEsc(c.location.displayName)}</p></div><div class="report-actions"><button class="btn btn-ghost" onclick="window.print()">Print</button><button class="btn btn-gold" onclick="downloadKundali()">Download JSON</button><button class="btn btn-ghost" onclick="resetKundali()" id="kundaliNewCalcBtn">${(typeof LANG!=='undefined'&&LANG==='ne')?'नयाँ कुण्डली':'New Kundali'}</button></div></div><div class="report-meta"><span>Latitude ${c.location.latitude.toFixed(4)}</span><span>Longitude ${c.location.longitude.toFixed(4)}</span><span>Timezone ${kundaliEsc(c.timezone)}</span><span>Ayanamsha Lahiri</span><span>UTC ${kundaliEsc(c.utc)}</span></div><div class="chart-grid">${kundaliChartSvg('D1 / Rashi Chart',c.planets)}${kundaliChartSvg('Bhava Chalit',c.planets)}${kundaliChartSvg('D9 / Navamsa',c.vargas.D9)}</div><div class="report-section"><h3>Planetary positions</h3><div class="table-scroll"><table><thead><tr><th>Planet</th><th>Sidereal sign</th><th>Degree</th><th>Nakshatra</th><th>House</th><th>Retrograde</th></tr></thead><tbody>${planetRows}</tbody></table></div></div><div class="report-columns"><div class="report-section"><h3>Panchanga at birth</h3><dl>${Object.entries(c.panchanga).map(([key,value])=>`<dt>${kundaliEsc(key)}</dt><dd>${kundaliEsc(value)}</dd>`).join('')}</dl></div><div class="report-section"><h3>Vimshottari Dasha</h3><p>Balance at birth: ${c.dasha.balanceYears.toFixed(2)} years</p>${c.dasha.periods.slice(0,6).map(d=>`<div class="dasha-row"><b>${d.name}</b><span>${d.start} - ${d.end}</span></div>`).join('')}</div></div><div class="report-section"><h3>Yoga and dosha checks</h3>${c.yogas.map(y=>`<div class="finding"><b>${kundaliEsc(y.name)}</b><span>${kundaliEsc(y.interpretation)}</span></div>`).join('')||'<p>No configured yoga rule triggered.</p>'}<div class="finding"><b>Manglik / Mangal Dosha</b><span>${c.doshas.manglik.present?'Present':'Not present'} from the D1 Mars placement; this is a calculation, not an absolute prediction.</span></div></div><p class="report-footnote">Reproducibility: ${kundaliEsc(c.method)} | Ephemeris: ${kundaliEsc(c.ephemeris)}</p></div>`;setTimeout(()=>{target.scrollIntoView({behavior:'smooth',block:'start'});},100);}
function downloadKundali(){const blob=new Blob([JSON.stringify(kundaliState.chart,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`kundali-${kundaliState.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.json`;link.click();URL.revokeObjectURL(link.href);}
function resetKundali(){Object.assign(kundaliState,{name:'',gender:'',dob:'',dobAd:'',dobBsYear:'',dobBsMonth:'',dobBsDay:'',tob:'',pob:'',country:'',language:'en',location:null,timezone:'',submitted:false,chart:null,error:''});const resultPanel=document.getElementById('kundaliChartPanel');if(resultPanel){resultPanel.style.display='none';resultPanel.innerHTML='';}renderKundali();window.scrollTo({top:0,behavior:'smooth'});}